spring:
  application:
    name: MSTxFleet-DBS-Postgis

  cloud:
    discovery:
      enabled: false
  datasource:
    username: ilisi
    password: ilisi
    url: jdbc:postgresql://localhost:5432/ilisi2023-2024
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092  # The address of your Kafka broker(s)
    consumer:
      auto-offset-reset: earliest  # Set the offset reset to 'earliest' or 'latest'
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer  # Key deserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer  # Value deserializer
      group-id: group_1
      enable-auto-commit: true
      properties:
          spring.json.trusted.packages: '*'



server:
  port: 0